--Teams
TEAMID	TEAMNAME	TOTALPOINTS
1	      Team A	  0
2	      Team B	  0
3	      Team C	  0
4	      Team D	  0

--Players
PLAYERID	PLAYERNAME	TEAMID	GOALSSCORED	ASSISTS	MATCHESPLAYED
1	        Player 1	  1	      0	          0	      0
2 	        Player 2	  1	      0	          0	      0
3	        Player 3	  2	      0	          0	      0
4	        Player 4	  3	      0	          0	      0


--Matches
MATCHID	TEAM1ID	TEAM2ID	TEAM1SCORE	TEAM2SCORE	MATCHDATE
1	      1	      2	      2	          1	          01-JAN-25
2	      3	      4	      0	          0	          02-JAN-25


--Pointstable
TEAMID	MATCHESPLAYED	WINS	DRAWS	LOSSES	POINTS
1	      0	            0	    0	    0	      0
2	      0	            0	    0	    0 	    0
3	      0	            0	    0	    0	      0
4	      0	            0	    0	    0	      0
